remote_theme: pmarsceill/just-the-docs
title: ''
search_enabled: true
aux_links:
    "Just the Docs on GitHub":
      - "//github.com/pmarsceill/just-the-docs"
    "Something else":
      - "//github.com/pmarsceill/just-the-docs"
    "Another something":
      - "//github.com/pmarsceill/just-the-docs"
